const { OAuth2Client } = require('google-auth-library')
const User = require('../models/User')
const { fail } = require('./errors')
const client = new OAuth2Client()

async function availableUsername(name) {
  const base = typeof name === 'string' && name.trim() ? name.trim() : 'Google user'
  let username = base
  let suffix = 2
  while (await User.exists({ username })) username = `${base} ${suffix++}`
  return username
}

async function googleLogin(credential) {
  if (!process.env.GOOGLE_CLIENT_ID) fail(503, 'Google login is not configured')
  if (typeof credential !== 'string' || !credential || credential.length > 10000) fail(400, 'Google credential is required')
  let payload
  try {
    const ticket = await client.verifyIdToken({ idToken: credential, audience: process.env.GOOGLE_CLIENT_ID })
    payload = ticket.getPayload()
  } catch {
    fail(401, 'Google sign-in could not be verified. Please try again.')
  }
  if (!payload?.sub || !payload.email || payload.email_verified !== true) fail(401, 'A verified Google email is required')
  const existing = await User.findOne({ googleId: payload.sub })
  if (existing) {
    // Replace names generated by the original UUID format on the next Google login.
    if (/_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(existing.username)) {
      const username = await availableUsername(payload.name)
      try {
        await User.updateOne({ _id: existing._id, username: existing.username }, { $set: { username } })
        existing.username = username
      } catch (error) { if (error.code !== 11000) throw error }
    }
    return existing
  }
  // Never attach Google credentials to an existing password account automatically.
  const email = payload.email.toLowerCase()
  const escapedEmail = email.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  if (await User.exists({ email: new RegExp(`^${escapedEmail}$`, 'i') })) {
    fail(409, 'An account with this email already exists. Please use your username and password.')
  }
  for (let attempt = 0; attempt < 3; attempt++) {
  const username = await availableUsername(payload.name)
  try {
    return await User.create({
      googleId: payload.sub,
      email,
      username,
      role: 'user'
    })
  } catch (error) {
    // Simultaneous first sign-ins should return the same Google account.
    if (error.code === 11000) {
      const user = await User.findOne({ googleId: payload.sub })
      if (user) return user
      if (error.keyPattern?.username) continue
      fail(409, 'An account with this email already exists. Please use your username and password.')
    }
    throw error
  }
  }
  fail(409, 'Please try signing in again.')
}
module.exports = { googleLogin }
